---
repos:
- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: check-yaml