---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-db
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: uzumlukek/titanic-db:latest
        ports:
        - containerPort: 5432
        # envFrom:
        # - secretRef:
        #     name: titanic-db-credentials
        # env:
        # - name: POSTGRES_DB
        #   valueFrom:
        #     configMapKeyRef:
        #       name: titanic-db-database
        #       key: POSTGRES_DB
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: titanic-db-database
# data:
#   POSTGRES_DB: postgres
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: titanic-db-credentials
# type: Opaque
# data:
#   POSTGRES_USER: dXNlcgo=
#   POSTGRES_PASSWORD: cGFzc3dvcmQK
---
apiVersion: v1
kind: Service
metadata:
  name: titanic-db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432